write code in branch stage-1
tspa77/market pull request #1
Opened 2018-02-13 19:08 UTC by tspa77

2018-02-14 09:18 UTC, bluzir commented on main.py
> +    url = "https://api.telegram.org/bot538702489:AAEZkKKJyaB-AYimhlxCawQ5ximbH22rIZ0/getUpdates"
Токен нужно будет убрать в файл настроек. На странице этапа про это написано

2018-02-14 09:19 UTC, bluzir commented on main.py
> +import requests
Убираем комменты и пробел сверху, импорт переносим на верх файла

2018-02-14 09:21 UTC, bluzir commented on main.py
> +        print(result[mess]['message']['from']['first_name'],': ', result[mess]['message']['text'] )
Не используй такие огромные строки — вспомни видео из первого урока и философию python. Все должно быть максимально просто и хорошо читаться. 

Вынеси имя и текст в разные переменные, а потом просто запринть уже их

2018-02-14 09:21 UTC, bluzir commented on main.py
> +print('Сеанс окончен')
В целом хорошо, начинай делать функцию для отправки сообщения.

2018-02-14 09:22 UTC, bluzir requested changes
В целом хорошо. Поправь, что я написал и начинай делать функцию для отправки сообщения.

2018-02-14 09:36 UTC, bluzir commented on main.py
> +    for mess in range(len(result)):
Слишком сложно — result итерируется напрямую, без длинны и ренжа

2018-02-14 09:42 UTC, tspa77 commented
Привет!
Не совсем понял, как здесь в переменные вынести.
result же итерируется через переменную mess
как
  result[mess]['message']['from']['first_name'],
или
  result[mess]['message']['text']
вынести в разные переменные, если у них внутри счётчик mess крутится?



2018-02-14 16:21 GMT+07:00 Vladislav Kooklev <notifications@github.com>:

> *@bluzir* commented on this pull request.
> ------------------------------
>
> In main.py <https://github.com/tspa77/market/pull/1#discussion_r168114608>
> :
>
> > +def get_bot_updates():
> +    url = "https://api.telegram.org/bot538702489:AAEZkKKJyaB-AYimhlxCawQ5ximbH22rIZ0/getUpdates"
> +    result = requests.get(url)
> +    pydict = result.json()
> +    return pydict['result']
> +
> +
> +result = get_bot_updates()
> +
> +
> +print('У вас {} сообщений'.format(len(result)))
> +answer = input("Хотите прочесть(Y/N)")
> +
> +if answer == 'Y':
> +    for mess in range(len(result)):
> +        print(result[mess]['message']['from']['first_name'],': ', result[mess]['message']['text'] )
>
> Не используй такие огромные строки — вспомни видео из первого урока и
> философию python. Все должно быть максимально просто и хорошо читаться.
>
> Вынеси имя и текст в разные переменные, а потом просто запринть уже их
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tspa77/market/pull/1#pullrequestreview-96427457>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AblhyP9pQ1gvC3E_CvF4siqz6fptV59fks5tUqWQgaJpZM4SEP-Y>
> .
>

2018-02-16 09:33 UTC, bluzir requested changes
В целом все хорошо. Можно начинать делать функции с запросами к АПИ и поделать правки.

2018-02-16 09:33 UTC, bluzir commented on main.py
> +    api_response = requests.get(bot_token + 'getUpdates', params)
URl для первого аругмента лучше хранить в переменной
В settings должен быть только токен, сама ссылка на АПИ должна быть в коде и к ней уже должен будет добавлять токен

2018-02-16 09:33 UTC, bluzir commented on main.py
> +    respon = requests.post(bot_token + 'sendMessage', params)
Тоже самое про ссылку, только токен импортируем

2018-02-16 09:33 UTC, bluzir commented on main.py
> +        print(" Фор-ин отработал или прошло 30 секунд. В любо случае ничё нового нет, переменные не трогаю, сижу, курю, жду апдейтов   ")
Очень длинный принт. Текст лучше вынести в переменную и сделать там переносы текста.

2018-02-16 09:33 UTC, bluzir commented on main.py
> +        for res_upd in result: # если есть что-то новое, то работаем дальше. Если нет - в конец вайла. Спим и курим.
res_upd — не очень понятное название 
result должен быть в множественном числе, их же много у нас

в идеале for result in results

2018-02-16 09:33 UTC, bluzir commented on main.py
> +            answer_text = last_chat_name + ', ты сказал: ' + last_chat_text
Это правильно. 

Но давай теперь сделаем еще лучше и будем использовать форматирование строк через format для соединения нескольких переменных и текста.

2018-02-16 09:33 UTC, bluzir commented on main.py
> +            print(newoffset, "  = newoffset = last_update_id   ", last_chat_text)
И тут можно format

2018-02-16 09:33 UTC, bluzir commented on main.py
> +    respon = requests.post(bot_token + 'sendMessage', params)
response давай назовем

2018-02-16 10:19 UTC, closed without merging