Stage 1
tspa77/market pull request #3
Opened 2018-02-18 03:52 UTC by tspa77

2018-02-18 09:32 UTC, bluzir requested changes
По функциям хороший код, давай двигаться в сторону упрощения и читабельности

2018-02-18 09:32 UTC, bluzir commented on main.py
> +    # # Нормальный подход или так не принято?
Да, комменты это хорошо, но каждую строчку комментить не обязатльно
Только для совсем уж неочевидных мест
Просто страаемся, чтобы код за счет названий функций и переменных был понятен и без комментов

2018-02-18 09:32 UTC, bluzir commented on main.py
> +    # # Нормальный подход или так не принято?
Хорошая функция

2018-02-18 09:32 UTC, bluzir commented on main.py
> +    api_response = requests.get(exchange_url + 'btc-usd')
Смотри, вот у тебя тут 4 раза целиком повторяется логика
Прямо напрашивается вынести это в функцию для получения курса и сохранения ее в словарик
Чтобы не 4 раза писали один код, а вызвали 4 раза фунцию с разными параметрами

2018-02-18 09:32 UTC, bluzir commented on main.py
> +            if last_chat_text == '/start':
Попробуй обработку комманд тоже вынести в отдельную функцию
Чтобы главный модуль содержал по минимуму логики, а скорее вызывал сторонние функции
Уточняй в чате. если будет непонятно

2018-02-23 19:49 UTC, bluzir approved these changes
Найс. После курса улучшать можно будет

2018-02-23 19:49 UTC, bluzir commented on main.py
> +    while True:
Огромная функция получилось — нужно разбивать на несколько

2018-02-23 19:49 UTC, bluzir commented on main.py
> +    if last_chat_text in answers_with_request:
Можно еще разбить функцию на несколько
Вынести вернее условие в другую функцию, чтобы не было вложенных условий вообще

Текст сообщений лучше вообще по словарю сверять, чтобы не разрасталась так функция и не было столько условий

2018-02-23 19:49 UTC, merged

2018-02-24 01:20 UTC, tspa77 commented on main.py
> +    if last_chat_text in answers_with_request:
Да, уже сам понял. Захотел сам (по другим тригерам) курс вывести, а понял, что такой функции как таковой нет, только блок ифов в ответ на сообщение :(
Ты скажи, в рамках обучения/проекта мы ещё будем к боту возвращаться?
Просто хотел как минимум в свою папку его переложить, а то он в корне проекта лежит, да и пилить потихоньку...